### PR TITLE
Allow web-api-only operation

### LINKED ISSUE #169: Nuki 3.0 Pro support without bridge
The release of the new Nuki 3.0 Pro with built in WiFi seems to not offer the built in bridge capabitlity and therefore no access to the bridge/http API. To get that, I guess I need to buy the bridge. But the device will offer the access to the WEB API.

_What I wrote above was also confirmed by the Nuki Support team._

Would there be the possibility to enable the web api "only"? I think currently your adapter needs to have the bridge/http api as pre-requesite, or?

Thanks for your help.

### PR DESCRIPTION
**Pull request by StrathCole**
Adapter does not work by default when no bridge is configured, fixes #169

### CODE REVIEW

**Comment by jhubig** [comment]
Tested with Nuki 3.0 Pro without having a bridge. Works like expected.
Maybe someone still using the bridge could give it a try if everything still works as expected. Thanks.

**Comment by StrathCole** [comment]
Tested with Nuki 3.0 pro and Bridge

**Comment by theimo1221** [comment]
@jhubig & @StrathCole could you please check if my update (which resolves the issues in automatic test, work in your live enviroments properly too?

**Comment by jhubig** [comment]
Hello Thiemo.

thanks. Works perfectly for me.
Just as reminder my setup, if needed.

- Nuki 3.0 Pro used without the bridge
- Node 14.18.1
- NPM 6.14.15
Thanks again.

**Pull request merged**
